version: '3'
services:
  reverseproxy:
    build:
      context: .
    image: mkhill/reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: mkhill/udagram-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed
    image: mkhill/udagram-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend
    image: mkhill/udagram-frontend:local
